### ISSUE TITLE
[Feature proposal] Support for custom clients / workers (e.g. written in c++)

### ISSUE THREAD

**Issue by mliszcz** [S2Innovation/sys-tango-benchmark#46]
I'd like to trigger a discussion regarding 'switchable' clients (workers).

@jkotan could you please comment on below proposal as you are the leading contributor?
I'd like to verify that proposed changes are in-line with sys-benchmark architecture and development plans.

CC @piogor - estimated effort to deliver this feature is 20h (16h for code adaption + 4h for cpp client).

In S2Innovation we would like to have a possibility to use a c++-based client (native binary) 
instead of current worker implementations (multiprocessing.Process). To keep a common interface for both python and c++ clients, I propose to replace `multiprocessing` with `subprocess` as follows:

* move workers to dedicated python scripts - e.g. a `Worker` from `readbenchmark.py` will be moved to `readworker.py`.
* worker will read parameters from `sys.argv` instead of current `__init__` method
  https://github.com/tango-controls/sys-tango-benchmark/blob/fb35310dba7dc386f6fa349e8abbfd3345778b81/benchmarks/tangobenchmarks/readbenchmark.py#L33-L38
* worker will start executing the scenario immediately (current `run` method)
  https://github.com/tango-controls/sys-tango-benchmark/blob/fb35310dba7dc386f6fa349e8abbfd3345778b81/benchmarks/tangobenchmarks/readbenchmark.py#L71-L73
* worker will print results to stdout (instead of `qresult.put(...)`). Proposed format:
  ```
  <wid> <counter> <time> <errors>
  ```
  https://github.com/tango-controls/sys-tango-benchmark/blob/fb35310dba7dc386f6fa349e8abbfd3345778b81/benchmarks/tangobenchmarks/readbenchmark.py#L88-L90
* worker must exit with `0`
* test configuration shall be extended with `worker` (`client`?) entry:
    ```yaml
    - benchmark: writebenchmark
      worker: /path/to/worker/executable
      title: "Python attribute write benchmark"
      clients: 4,8,16,32,64,128
      device: test/pybenchmarktarget/01
      period: 10
    ````
* TBD: if we want to have mixed traffic models in future we may define `clients` as array:
    ```yaml
    clients:
      - worker: workers/python/writer.py
        num: 4
      - worker: workers/cpp/reader.exe
        num: 8
    ```
* instead of `Worker` instances, benchmark will store information how to start worker (e.g. an array with executable and parameters):
    https://github.com/tango-controls/sys-tango-benchmark/blob/fb35310dba7dc386f6fa349e8abbfd3345778b81/benchmarks/tangobenchmarks/readbenchmark.py#L115-L119
    will be replaced by:
    ```python
        self._workers = [
            [self.__worker, i, self__device, self.__attribute, self.__period]
            for i in range(self.__clients)
        ]
    ```
* current process management shall be replaced from
    https://github.com/tango-controls/sys-tango-benchmark/blob/fb35310dba7dc386f6fa349e8abbfd3345778b81/benchmarks/tangobenchmarks/utils.py#L49-L55
    to
    ```python
    self.__processes = [Popen(args, stdout = PIPE) for args in self.__workers]
    for p in self.__processes: p.wait()
    ```
* results must be read from a pipe, e.g. instead of
    https://github.com/tango-controls/sys-tango-benchmark/blob/fb35310dba7dc386f6fa349e8abbfd3345778b81/benchmarks/tangobenchmarks/utils.py#L57-L67
    use
    ```python
    self.__results = []
    for p in self.__processes:
        out, _ = p.communicate()
        self.__results.append(makeResultFromString(out))
    ```

BTW if we decouple workers from benchmarks as proposed above, we can also do some refactoring and remove all derived benchmark classes, leaving only base `Benchmark` class (from `utils.py`). There is quite a lot of code duplicated in each benchmark and it seems that the only purpose of derived benchmarks is to provide custom labels for RST output.

**Comment by jkotan** [comment]
Hi Michał,

Sure, you can do it.

In my opinion using `subprocess` is less pythonic than `Process`. But if you want to run it with external works you don't have to much choice (In original request external workers were not mentioned).

**Comment by jkotan** [comment]
I think more pythonic would be to run python workers in `Process` while other external works in `subprocess`.

**Comment by mliszcz** [comment]
Hi Jan.
Thanks for your inputs!

Regarding your proposal to keep `multiprocessing.Process` interface and to add new interface for non-Python workers - is there any benefit of such approach (except for being more 'pythonic')?

For external clients, we need new `subprocess` interface - this is clear now. But Python clients can also use `subprocess` interface. There's no point in keeping two interfaces - it's just extra maintenance cost (keeping old and new IF in sync) and additional code complexity (probably a few `if`s more). Also, if we want to have feature parity between Python and non-Python clients, we will always be limited by `subprocess` interface and we will never utilize full potential of `multiprocessing` module.

Another idea - we could keep Python workers as `multiprocessing.Process` and for non-Python workers we can have a class `ExternalWorker` which will wrap `subprocess.Popen` in `Process`-like interface (`start()`, `join()`, etc.). Anyway, it's still more complex than talking to Python and non-Python workers in the same way.

BTW if we move Python workers to external scripts, we could probably remove Tango dependency from benchmark runner (not sure about server autostarting feature). Clients could be placed in docker containers while runner can still be outside - interacting with runner may be simpler (e.g. no need for scripts like `run-with-params.sh`).

What do you think?

**Comment by jkotan** [comment]
Hi Michał,

For me python programs live more in python packages/modules than in separate files. Thus, if you want to provide an external worker a better solution would be to distribute it in a package/module as a specific class. Then the runner could register the worker class point by package.module. You don't have to take care about a filesystem path. It is enough the worker is in `PYTHONPATH` so it is more system independent.

Usually people avoid to call python from python via `subprocess` command unless they have serious excuse: https://stackoverflow.com/questions/13606867/what-is-the-difference-between-multiprocessing-and-subprocess

Yes, for me wrapping of `subprocess.Popen` to the `Process`-like interface would be one of solutions.

I don't think you can remove Tango dependencies from the benchmark runner (unless you make it not self-usable).

**Comment by jkotan** [comment]
It could be also interesting co compare works based on `Process` to  workers based  on `Thread` on the client side. In some cases `Thread` could be faster.

**Comment by jkotan** [comment]
But of course `subprocess` solution could be easier to implement (except passing back results). So the choice is yours.

**Comment by mliszcz** [comment]
Hi Jan,

> But of course `subprocess` solution could be easier to implement (except passing back results). So the choice is yours.

I need to implement `subprocess` solution for cpp-based workers anyway. My point was that it will not make sense to keep `multiprocessing` interface if we have more generic (but less pythonic) `subprocess` interface.

Anyway, if we're going to implement support for cpp-based clients, I will try to leave python-based workers as they are now (accessed via `multiprocessing`). We can decide later whether we shall keep separate interfaces or not.
