### ISSUE TITLE
README udpate with the recent benchmarks implemented

### ISSUE THREAD

**Issue by piogor** [S2Innovation/sys-tango-benchmark#62]
The following benchmarks are added:
- [ ] #14 
- [ ] #13 
- [ ] #12

**Comment by mliszcz** [comment]
#13 / #61 is not on master.
#60 (fixes #12) was a PR for master.
#61 (fixes #13) was PR for #60 branch (needed some code from #60).
Probably #60 was merged first and changes from #61 are not visible.

Edit: I've opened #63 to fix this.
